"""Explicit V2 identity axes, handover ledger, and public authority resolver."""

from __future__ import annotations

import hashlib
import json
import uuid
from dataclasses import dataclass, field
from typing import Any, Mapping


INTEGRITY_STATUSES = (
    "EXACT",
    "AXIS_MISMATCH",
    "SOURCE_RUN_MISMATCH",
    "SESSION_MISMATCH",
    "AMBIGUOUS_ONE_TO_MANY",
    "COLLISION",
    "STALE_MAPPING",
    "MISSING_PROVENANCE",
)
CANDIDATE_ASSIGNMENT_STATUSES = (
    "ASSIGNED_TO_EXISTING_PUBLIC",
    "ASSIGNED_TO_NEW_PUBLIC",
    "UNASSIGNED_CANDIDATE",
    "REJECTED_BELOW_THRESHOLD",
    "CANDIDATE_ONLY_NO_PUBLIC_AUTHORITY",
)
PUBLIC_ASSIGNMENT_STATUSES = (
    "ASSIGNED_CANDIDATE",
    "EXPLICIT_NONE",
    "PUBLIC_STATE_NOT_PRESENT",
    "PUBLIC_ASSIGNMENT_ARTIFACT_ABSENT",
)
ALLOWED_PUBLIC_SOURCES = frozenset(
    {
        "identity_registry_binding",
        "explicit_runtime_assignment",
        "direct_user_public_id",
        "frozen_provenance_mapping",
        "track_manager_mot_output",
    }
)


def _text(value: Any) -> str | None:
    return value.strip() if isinstance(value, str) and value.strip() else None


def _digest(payload: Mapping[str, Any]) -> str:
    encoded = json.dumps(
        dict(payload), sort_keys=True, separators=(",", ":"), ensure_ascii=False, allow_nan=False
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


class MappingV2Error(ValueError):
    pass


@dataclass
class HandoverLedger:
    """A same-run segment/local/global binding ledger.

    Local and global IDs are opaque tokens generated by this ledger, not raw
    SAM IDs and not public IDs.  Cross-segment continuity is only exact when a
    caller supplies an explicit token/transaction; absent continuity remains
    unresolved instead of being linked by IoU or appearance.
    """

    source_run_id: str
    sequence: str
    session_id: str
    segment_id: str
    window_id: str = "window-0"
    chunk_id: str = "chunk-0"
    _segment_by_adapter: dict[int, str] = field(default_factory=dict)
    _global_by_local: dict[str, str] = field(default_factory=dict)
    transactions: list[dict[str, Any]] = field(default_factory=list)
    unresolved: list[dict[str, Any]] = field(default_factory=list)

    def __post_init__(self) -> None:
        for key in ("source_run_id", "sequence", "session_id", "segment_id", "window_id", "chunk_id"):
            if _text(getattr(self, key)) is None:
                raise MappingV2Error(f"missing ledger field: {key}")

    def bind_segment(self, adapter_external_id: int, *, transaction_id: str | None = None) -> str:
        adapter_external_id = int(adapter_external_id)
        current = self._segment_by_adapter.get(adapter_external_id)
        if current is not None:
            return current
        transaction_id = transaction_id or str(uuid.uuid4())
        token = "seg-" + _digest(
            {
                "schema": "N72R1_SEGMENT_LOCAL_ID_V1",
                "source_run_id": self.source_run_id,
                "sequence": self.sequence,
                "session_id": self.session_id,
                "segment_id": self.segment_id,
                "adapter_external_id": adapter_external_id,
            }
        )[:32]
        self._segment_by_adapter[adapter_external_id] = token
        self.transactions.append(
            {
                "transaction_id": transaction_id,
                "type": "adapter_to_segment_local",
                "source_run_id": self.source_run_id,
                "session_id": self.session_id,
                "segment_id": self.segment_id,
                "adapter_external_id": adapter_external_id,
                "segment_local_id": token,
                "source": "segment_authoritative_adapter_binding",
            }
        )
        return token

    def bind_global(
        self,
        segment_local_id: str,
        *,
        continuity_token: str | None = None,
        previous_global_id: str | None = None,
        transaction_id: str | None = None,
    ) -> str | None:
        local = _text(segment_local_id)
        if local is None:
            raise MappingV2Error("segment_local_id is required")
        current = self._global_by_local.get(local)
        if current is not None:
            return current
        if previous_global_id is not None and not _text(continuity_token):
            item = {
                "type": "local_to_global_unresolved",
                "source_run_id": self.source_run_id,
                "session_id": self.session_id,
                "segment_id": self.segment_id,
                "segment_local_id": local,
                "previous_global_id": previous_global_id,
                "status": "UNRESOLVED_LOCAL_TO_GLOBAL",
                "reason": "continuity_token_missing",
            }
            self.unresolved.append(item)
            return None
        transaction_id = transaction_id or str(uuid.uuid4())
        token = "global-" + _digest(
            {
                "schema": "N72R1_SEQUENCE_GLOBAL_ID_V1",
                "source_run_id": self.source_run_id,
                "sequence": self.sequence,
                "segment_local_id": local,
                "continuity_token": continuity_token,
                "previous_global_id": previous_global_id,
            }
        )[:32]
        self._global_by_local[local] = token
        self.transactions.append(
            {
                "transaction_id": transaction_id,
                "type": "segment_local_to_sequence_global",
                "source_run_id": self.source_run_id,
                "session_id": self.session_id,
                "segment_id": self.segment_id,
                "segment_local_id": local,
                "sequence_global_id": token,
                "continuity_token_present": bool(_text(continuity_token)),
                "previous_global_id": previous_global_id,
                "source": "explicit_continuity_token" if continuity_token else "same_segment_authoritative_binding",
            }
        )
        return token

    def axes_for(self, adapter_external_id: int, *, previous_global_id: str | None = None, continuity_token: str | None = None) -> tuple[str, str | None]:
        local = self.bind_segment(adapter_external_id)
        global_id = self.bind_global(
            local,
            previous_global_id=previous_global_id,
            continuity_token=continuity_token,
        )
        return local, global_id

    def audit(self) -> dict[str, Any]:
        return {
            "schema_version": "N72R1_LOCAL_GLOBAL_HANDOVER_V1",
            "source_run_id": self.source_run_id,
            "sequence": self.sequence,
            "session_id": self.session_id,
            "segment_id": self.segment_id,
            "window_id": self.window_id,
            "chunk_id": self.chunk_id,
            "adapter_binding_count": len(self._segment_by_adapter),
            "global_binding_count": len(self._global_by_local),
            "transactions": list(self.transactions),
            "unresolved": list(self.unresolved),
            "status": "PASS" if not self.unresolved else "PARTIAL_MULTI_CHUNK_HANDOVER_UNRESOLVED",
        }


class PublicAuthorityResolver:
    """Resolve association states only from an explicit runtime bridge."""

    def __init__(self, *, source_run_id: str, session_id: str) -> None:
        if _text(source_run_id) is None or _text(session_id) is None:
            raise MappingV2Error("source_run_id and session_id are required")
        self.source_run_id = str(source_run_id)
        self.session_id = str(session_id)
        self._bindings: dict[int, dict[str, Any]] = {}

    def bind(
        self,
        association_state_id: int,
        public_id: int,
        *,
        source: str,
        transaction_id: str,
        source_run_id: str | None = None,
        session_id: str | None = None,
    ) -> None:
        if source not in ALLOWED_PUBLIC_SOURCES:
            raise MappingV2Error(f"public authority source is not allowed: {source}")
        if _text(transaction_id) is None:
            raise MappingV2Error("explicit public binding needs transaction_id")
        if source_run_id is not None and str(source_run_id) != self.source_run_id:
            raise MappingV2Error("source_run mismatch in public binding")
        if session_id is not None and str(session_id) != self.session_id:
            raise MappingV2Error("session mismatch in public binding")
        state_id = int(association_state_id)
        pid = int(public_id)
        previous = self._bindings.get(state_id)
        if previous is not None and int(previous["public_id"]) != pid:
            raise MappingV2Error("association state has conflicting public bindings")
        for other_state, item in self._bindings.items():
            if other_state != state_id and int(item["public_id"]) == pid:
                raise MappingV2Error("public ID is already bound to another association state")
        self._bindings[state_id] = {
            "association_state_id": state_id,
            "public_id": pid,
            "source": source,
            "transaction_id": str(transaction_id),
            "source_run_id": self.source_run_id,
            "session_id": self.session_id,
        }

    def resolve(self, association_state_id: int) -> int | None:
        item = self._bindings.get(int(association_state_id))
        return None if item is None else int(item["public_id"])

    def binding(self, association_state_id: int) -> dict[str, Any] | None:
        item = self._bindings.get(int(association_state_id))
        return None if item is None else dict(item)

    def audit(self) -> dict[str, Any]:
        return {
            "schema_version": "N72R1_PUBLIC_AUTHORITY_RESOLVER_V1",
            "source_run_id": self.source_run_id,
            "session_id": self.session_id,
            "binding_count": len(self._bindings),
            "bindings": [dict(self._bindings[key]) for key in sorted(self._bindings)],
            "numeric_fallback_used": False,
        }


def resolve_public_id(
    association_state_id: int,
    *,
    resolver: PublicAuthorityResolver | None,
) -> int | None:
    """Resolve through the explicit bridge or return ``None``."""

    if resolver is None:
        return None
    return resolver.resolve(int(association_state_id))


__all__ = [
    "ALLOWED_PUBLIC_SOURCES",
    "CANDIDATE_ASSIGNMENT_STATUSES",
    "HandoverLedger",
    "INTEGRITY_STATUSES",
    "MappingV2Error",
    "PUBLIC_ASSIGNMENT_STATUSES",
    "PublicAuthorityResolver",
    "resolve_public_id",
]
