#!/usr/bin/env python3
"""N24 first temporal identity diagnostic.

Evaluate the same real SAM3 candidate groups at 1/5/10/20 causal evidence
frames.  Candidate features are recovered by IoU matching each shadow box to
the frozen GFN and R0 galleries already used by N18--N23.  Ground truth is
used only to identify the positive candidate for post-hoc ranking metrics;
neither candidate construction nor feature extraction uses it.

The diagnostic deliberately measures a transparent temporal prototype before
introducing a learned reasoner:

    prototype_H = normalize(mean_t embedding_t),
    score_H = prototype_H dot human_root.

For H=1 this is the single-frame baseline.  The same groups are evaluated at
all four H values, so a change is attributable to temporal evidence rather
than a change in candidate denominator.  The input directory should contain
the N24 horizon-20 shadow subset generated by run_n20_all_candidate_shadow.py.
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path

import numpy as np

ROOT = Path(".")
GFN_CACHE = ROOT / "outputs/n18/route_c/gfn_cache"
R0_CACHE = ROOT / "outputs/n20/gfn_cache_r0"


def normalize(x: np.ndarray) -> np.ndarray:
    x = np.asarray(x, dtype=np.float32)
    return x / (np.linalg.norm(x, axis=-1, keepdims=True) + 1e-8)


def iou(a: np.ndarray, b: np.ndarray) -> float:
    ax1, ay1, ax2, ay2 = [float(v) for v in a]
    bx1, by1, bx2, by2 = [float(v) for v in b]
    ix1, iy1 = max(ax1, bx1), max(ay1, by1)
    ix2, iy2 = min(ax2, bx2), min(ay2, by2)
    inter = max(0.0, ix2 - ix1) * max(0.0, iy2 - iy1)
    aa = max(1e-8, (ax2 - ax1) * (ay2 - ay1))
    bb = max(1e-8, (bx2 - bx1) * (by2 - by1))
    return inter / max(1e-8, aa + bb - inter)


class SequenceCache:
    def __init__(self, seq: str):
        z = np.load(GFN_CACHE / f"{seq}.npz")
        qz = np.load(GFN_CACHE / f"{seq}_queries.npz")
        rz = np.load(R0_CACHE / f"{seq}.npz")
        self.frames = z["frames"].astype(np.int64)
        self.offsets = z["offsets"].astype(np.int64)
        self.boxes = z["boxes"].astype(np.float32)
        self.gfn = normalize(z["emb"].astype(np.float32))
        self.r0 = normalize(rz["r0g"].astype(np.float32))
        self.qgids = [int(v) for v in qz["gids"]]
        self.qindex = {gid: i for i, gid in enumerate(self.qgids)}
        self.qgfn = normalize(qz["qemb"].astype(np.float32))
        self.qr0 = normalize(rz["r0q"].astype(np.float32))
        z.close()
        qz.close()
        rz.close()

    def query(self, gid: int):
        idx = self.qindex.get(int(gid))
        if idx is None:
            return None
        return self.qgfn[idx], self.qr0[idx]

    def detection(self, frame: int, box):
        if box is None:
            return None
        pos = int(np.searchsorted(self.frames, int(frame)))
        if pos >= len(self.frames) or int(self.frames[pos]) != int(frame):
            return None
        lo = int(self.offsets[pos - 1]) if pos else 0
        hi = int(self.offsets[pos])
        if hi <= lo:
            return None
        box = np.asarray(box, dtype=np.float32)
        vals = np.asarray([iou(x, box) for x in self.boxes[lo:hi]])
        best = int(np.argmax(vals))
        if float(vals[best]) < 0.5:
            return None
        idx = lo + best
        return self.gfn[idx], self.r0[idx], float(vals[best])


def read_rows(input_dir: Path):
    rows = []
    for path in sorted(input_dir.glob("*.jsonl")):
        with path.open(encoding="utf-8") as handle:
            for line in handle:
                if line.strip():
                    rows.append(json.loads(line))
    return rows


def score_history(row, z: SequenceCache, root, history: int):
    seq = row["sequence"]
    f0 = int(row["frame"])
    gfn_vecs = []
    r0_vecs = []
    matched = 0
    observed = 0
    for fr in row.get("frames", []):
        ff = int(fr["frame"])
        if ff < f0 or ff >= f0 + history:
            continue
        observed += int(fr.get("box") is not None)
        de = z.detection(ff, fr.get("box"))
        if de is None:
            continue
        gfn_vecs.append(de[0])
        r0_vecs.append(de[1])
        matched += 1
    if not gfn_vecs:
        return {
            "gfn_last": float("nan"), "gfn_mean": float("nan"),
            "gfn_proto": float("nan"), "r0_last": float("nan"),
            "r0_mean": float("nan"), "r0_proto": float("nan"),
            "fused_proto": float("nan"), "matched": 0,
            "observed": observed, "coverage": 0.0,
        }
    gfn = np.asarray(gfn_vecs, dtype=np.float32)
    r0 = np.asarray(r0_vecs, dtype=np.float32)
    gfn_sims = gfn @ root[0]
    r0_sims = r0 @ root[1]
    gfn_proto = normalize(gfn.mean(axis=0, keepdims=True))[0]
    r0_proto = normalize(r0.mean(axis=0, keepdims=True))[0]
    fused = normalize(np.concatenate([gfn.mean(axis=0), r0.mean(axis=0)])[None])[0]
    fused_root = normalize(np.concatenate([root[0], root[1]])[None])[0]
    return {
        "gfn_last": float(gfn_sims[-1]),
        "gfn_mean": float(gfn_sims.mean()),
        "gfn_proto": float(gfn_proto @ root[0]),
        "r0_last": float(r0_sims[-1]),
        "r0_mean": float(r0_sims.mean()),
        "r0_proto": float(r0_proto @ root[1]),
        "fused_proto": float(fused @ fused_root),
        "matched": matched,
        "observed": observed,
        "coverage": float(matched / max(1, history)),
    }


def ranking_metrics(group_rows, score_key: str):
    ranks = []
    margins = []
    positive_scores = []
    negative_scores = []
    for rows in group_rows:
        valid = [r for r in rows if np.isfinite(r[score_key])]
        positives = [r for r in valid if int(r["positive"]) == 1]
        negatives = [r for r in valid if int(r["positive"]) == 0]
        if not positives or not negatives:
            continue
        valid.sort(key=lambda x: (-float(x[score_key]), int(x["rank"])))
        pos_indices = [i for i, r in enumerate(valid)
                       if int(r["positive"]) == 1]
        rank = min(pos_indices) + 1
        ranks.append(rank)
        pscore = max(float(r[score_key]) for r in positives)
        nscore = max(float(r[score_key]) for r in negatives)
        margins.append(pscore - nscore)
        positive_scores.append(pscore)
        negative_scores.extend(float(r[score_key]) for r in negatives)
    n = len(ranks)
    return {
        "groups": n,
        "top1": float(sum(r == 1 for r in ranks) / max(1, n)),
        "top3": float(sum(r <= 3 for r in ranks) / max(1, n)),
        "top5": float(sum(r <= 5 for r in ranks) / max(1, n)),
        "mrr": float(np.mean([1.0 / r for r in ranks])) if ranks else 0.0,
        "mean_positive_margin": float(np.mean(margins)) if margins else 0.0,
        "median_positive_margin": float(np.median(margins)) if margins else 0.0,
        "mean_positive_score": float(np.mean(positive_scores)) if positive_scores else 0.0,
        "mean_negative_score": float(np.mean(negative_scores)) if negative_scores else 0.0,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input-dir", default="outputs/n20/n24_diag_shadow20")
    ap.add_argument("--out-dir", default="outputs/n24/temporal_diagnostic")
    ap.add_argument("--histories", default="1,5,10,20")
    args = ap.parse_args()
    input_dir = Path(args.input_dir)
    if not input_dir.is_absolute():
        input_dir = ROOT / input_dir
    out_dir = Path(args.out_dir)
    if not out_dir.is_absolute():
        out_dir = ROOT / out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    histories = [int(x) for x in args.histories.split(",")]
    rows = read_rows(input_dir)
    if not rows:
        raise SystemExit(f"no JSONL rows under {input_dir}")
    # The diagnostic directory is intended to be a dedicated horizon-20 run.
    # Deduplicate safely if a shard was resumed or copied.
    unique = {}
    for row in rows:
        key = (row["sequence"], int(row["frame"]), int(row["gid"]),
               int(row["candidate_rank"]))
        old = unique.get(key)
        if old is None or len(row.get("frames", [])) > len(old.get("frames", [])):
            unique[key] = row
    rows = list(unique.values())
    attempts = defaultdict(list)
    for row in rows:
        attempts[(row["sequence"], int(row["frame"]), int(row["gid"]))].append(row)
    zcache = {}
    detail = []
    summary = []
    for attempt, cand_rows in sorted(attempts.items()):
        seq, f0, gid = attempt
        if seq not in zcache:
            zcache[seq] = SequenceCache(seq)
        z = zcache[seq]
        root = z.query(gid)
        if root is None:
            continue
        has_positive = any(int(r.get("is_correct", 0)) == 1 for r in cand_rows)
        if not has_positive:
            continue
        for history in histories:
            for row in cand_rows:
                scores = score_history(row, z, root, history)
                out = {
                    "sequence": seq, "frame": f0, "gid": gid,
                    "history": history,
                    "rank": int(row["candidate_rank"]),
                    "positive": int(row.get("is_correct", 0)),
                    "traj_len": int(row.get("traj_len", 0)),
                    **scores,
                }
                detail.append(out)
    by_h = defaultdict(list)
    for row in detail:
        by_h[int(row["history"])].append(row)
    methods = ["gfn_last", "gfn_mean", "gfn_proto", "r0_last", "r0_mean",
               "r0_proto", "fused_proto"]
    for history in histories:
        hrows = by_h[history]
        groups = defaultdict(list)
        for row in hrows:
            groups[(row["sequence"], row["frame"], row["gid"])].append(row)
        group_rows = list(groups.values())
        for method in methods:
            metrics = ranking_metrics(group_rows, method)
            coverage = [float(r["coverage"]) for r in hrows]
            matched = [int(r["matched"]) for r in hrows]
            summary.append({
                "history": history, "method": method,
                "candidate_rows": len(hrows),
                "attempt_groups": len(group_rows),
                "mean_feature_coverage": float(np.mean(coverage)) if coverage else 0.0,
                "mean_matched_frames": float(np.mean(matched)) if matched else 0.0,
                **metrics,
            })
    detail_path = out_dir / "n24_temporal_diagnostic_rows.csv"
    if detail:
        fields = list(detail[0].keys())
        with detail_path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=fields)
            writer.writeheader()
            writer.writerows(detail)
    summary_path = out_dir / "n24_temporal_diagnostic_summary.csv"
    if summary:
        fields = list(summary[0].keys())
        with summary_path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=fields)
            writer.writeheader()
            writer.writerows(summary)
    positive_groups = {
        (r["sequence"], r["frame"], r["gid"])
        for r in by_h[histories[0]]
        if int(r["positive"]) == 1
    }
    meta = {
        "input_dir": str(input_dir), "unique_candidate_rows": len(rows),
        "attempt_groups": len(attempts),
        "positive_attempt_groups": len(positive_groups),
        "histories": histories, "methods": methods,
        "detail_csv": str(detail_path), "summary_csv": str(summary_path),
        "label_policy": "row is_correct is used only as post-hoc candidate identity label",
        "feature_policy": "frozen GFN/R0 cache matched to real SAM3 shadow boxes by IoU >= 0.5",
    }
    (out_dir / "n24_temporal_diagnostic_meta.json").write_text(
        json.dumps(meta, indent=2), encoding="utf-8")
    print(json.dumps(meta, indent=2), flush=True)
    for row in summary:
        if row["method"] in ("gfn_proto", "r0_proto", "fused_proto"):
            print(json.dumps(row), flush=True)
    print("N24_TEMPORAL_DIAGNOSTIC_DONE", flush=True)


if __name__ == "__main__":
    main()
