"""Preserve the first N70 mapping/cache integrity failure before a repair.

This is an audit artifact writer only.  It never changes N36/N69 inputs and it
does not reinterpret the failed rows; it records the exact files and hashes
that will otherwise be regenerated by the targeted mapping regression.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import tempfile
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs/N70"
ATTEMPTS = OUT / "attempts"


def sha256(path: Path) -> str | None:
    if not path.is_file():
        return None
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def atomic_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, ensure_ascii=False, indent=2, sort_keys=True, allow_nan=False)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_name, path)
        dfd = os.open(str(path.parent), os.O_DIRECTORY)
        try:
            os.fsync(dfd)
        finally:
            os.close(dfd)
    finally:
        if os.path.exists(temp_name):
            os.unlink(temp_name)


def main() -> None:
    ATTEMPTS.mkdir(parents=True, exist_ok=True)
    source_names = (
        "diagnosis/mapping_audit.jsonl",
        "diagnosis/mapping_summary.json",
        "diagnosis/mapping_fixture_results.json",
        "cache/candidate_cache_manifest.json",
        "cache/candidate_cache_audit.json",
        "stage_01_status.json",
        "stage_02_status.json",
    )
    preserved: list[dict[str, object]] = []
    for relative in source_names:
        source = OUT / relative
        if not source.is_file():
            preserved.append({"path": str(source), "exists": False, "sha256": None})
            continue
        destination = ATTEMPTS / "mapping_cache_attempt1" / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        preserved.append({
            "path": str(source),
            "preserved_copy": str(destination),
            "exists": True,
            "bytes": source.stat().st_size,
            "sha256": sha256(source),
        })
    summary = json.loads((OUT / "diagnosis/mapping_summary.json").read_text(encoding="utf-8"))
    audit = json.loads("[" + ",".join(
        line for line in (OUT / "diagnosis/mapping_audit.jsonl").read_text(encoding="utf-8").splitlines() if line.strip()
    ) + "]")
    error_rows = [row for row in audit if row.get("mapping_errors")]
    categories: dict[str, int] = {}
    for row in error_rows:
        for reason in row.get("mapping_errors", []):
            categories[str(reason)] = categories.get(str(reason), 0) + 1
    atomic_json(ATTEMPTS / "n70_stage01_mapping_attempt1_failure.json", {
        "schema": "N70_MAPPING_ATTEMPT_FAILURE_V1",
        "status": "FAIL_PRESERVED_BEFORE_MINIMAL_REPAIR",
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "stage": "N70_STAGE_01_MAPPING_PROVENANCE",
        "root_cause": "The first audit treated zero-area boxes with identical coordinates as mismatched because box_iou returns 0 when union is zero.",
        "evidence": {
            "mapping_summary_status": summary.get("status"),
            "mapping_error_frames": summary.get("mapping_error_frames"),
            "chain_complete_frames": summary.get("chain_complete_frames"),
            "target_candidate_absent_frames": summary.get("target_candidate_absent_frames"),
            "audit_rows": len(audit),
            "error_rows": len(error_rows),
            "error_categories": categories,
        },
        "preserved_files": preserved,
        "repair_scope": "Only add explicit coordinate-equivalence handling for degenerate boxes in the N70 bridge; retain raw IoU and keep genuinely different boxes as failures.",
        "runtime_future_gt_used": False,
        "interaction_source": "simulated_from_gt",
        "real_human_tape": False,
        "real_sam3_full_loop": False,
        "production_authorized": False,
    })
    print(json.dumps({"status": "PRESERVED", "artifact": str(ATTEMPTS / "n70_stage01_mapping_attempt1_failure.json"), "error_rows": len(error_rows), "categories": categories}, sort_keys=True))


if __name__ == "__main__":
    main()
