#!/usr/bin/env python
"""N20.3: Oracle Delayed-Commit FULL_LOOP (CPU simulation).

The loop is the N19 learned-memory FULL_LOOP (Writer V0 T=0.95, K=2, Human
Root seed), but recovery commits are replaced by oracle shadow commits:

  LOST -> look up the precomputed real SAM3 shadow trajectory of the
  correct top-K candidate -> run the loop forward H frames -> if the shadow
  is still GT-correct at frame f+H, atomically commit (publish the shadow
  trajectory from f+H onward, same public ID).  No future GT is used for
  delivery; GT is used only for the offline oracle verdict, exactly as in
  the N19 oracle runs.

Shadow trajectories were generated by scripts/run_n20_oracle_shadow.py with
real isolated SAM3 sessions and are keyed by (sequence, frame, gid).
"""

import argparse
import csv
import json
import sys
import time
from collections import defaultdict
from pathlib import Path

import numpy as np
import torch

ROOT = Path(".")
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

from n19_writer_features import feature_names, to_feature_vec  # noqa: E402
from gfn_recovery_model import load_model  # noqa: E402
from run_n18_full_loop_v0 import load_gt, load_p0  # noqa: E402
from sam3_intermot.evaluation.full_loop_v0 import (  # noqa: E402
    LoopConfig, aggregate_metrics, iou, run_full_loop)
from train_n19_writer import WriterMLP  # noqa: E402

N19 = ROOT / "outputs/n19"
N20 = ROOT / "outputs/n20"
CACHE = ROOT / "outputs/n18/route_c/gfn_cache"


def to_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return float("nan")


def head_embed(model, f4, f5):
    with torch.inference_mode():
        emb, _ = model.roi_heads.embedding_head(
            {"feat_res4": f4, "feat_res5": f5})
    return emb / (emb.norm(dim=1, keepdim=True) + 1e-8)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--split", default="cal10", choices=["cal10", "train30"])
    ap.add_argument("--seqs", default="")
    ap.add_argument("--k", type=int, default=5)
    ap.add_argument("--horizon", type=int, default=8)
    ap.add_argument("--shard", type=int, default=0)
    ap.add_argument("--nshards", type=int, default=1)
    ap.add_argument("--out-tag", default="")
    ap.add_argument("--dump-only", action="store_true",
                    help="run with an empty shadow cache and no commits "
                         "(generates the no-commit attempt distribution)")
    ap.add_argument("--limit-frames", type=int, default=0)
    ap.add_argument("--learned-verifier", default="")
    ap.add_argument("--verifier-threshold", type=float, default=0.5)
    ap.add_argument("--kplus1-model", default="")
    ap.add_argument("--kplus1-dataset", default="")
    ap.add_argument("--kplus1-cache-dir", default="full_shadow_cache_cal10")
    ap.add_argument("--kplus1-margin", type=float, default=0.05)
    args = ap.parse_args()

    frozen = json.loads(
        (ROOT / "outputs/n15/n15_frozen.json").read_text())["split"]
    if args.seqs:
        seqs = sorted(args.seqs.split(","))
    else:
        seqs = sorted(frozen["train30" if args.split == "train30"
                                 else "calibration10"])
    seqs = seqs[args.shard:: args.nshards]
    tag = args.out_tag or f"oracle_delayed_k{args.k}_h{args.horizon}"

    cfg = LoopConfig(
        reactivation_horizon=120,
        enable_recovery=True,
        enable_reactivation=True,
        anchor_policy="learned",
        anchor_score=0.95,
        memory_k=2,
        shadow_mode=True,
        shadow_horizon=args.horizon,
        shadow_timeout=max(2 * args.horizon + 5, 30),
    )

    # ---- Writer V0 (CPU)
    wcfg = json.loads((N19 / "models/writer_v0/writer_config.json").read_text())
    writer = WriterMLP(len(feature_names()), hidden=wcfg["hidden"])
    writer.load_state_dict(torch.load(
        N19 / "models/writer_v0/writer_v0.pt", map_location="cpu"))
    writer.eval()
    mean = np.asarray(wcfg["scaler_mean"], dtype=np.float32)
    std = np.asarray(wcfg["scaler_std"], dtype=np.float32)

    gfn, _, _, _, _ = load_model("cpu")
    gfn.eval()
    r0_path = ROOT / "outputs/n18/route_c/models/r0_best.pt"
    if r0_path.exists():
        gfn.roi_heads.embedding_head.load_state_dict(
            torch.load(r0_path, map_location="cpu"))
        gfn.roi_heads.embedding_head.eval()

    # ---- shadow cache index
    shadow_idx = {}
    shadow_idx_k = {}
    if not args.dump_only:
        # The shadow cache is generated once for K=5; the K filter below
        # (`rank_mem <= args.k`) selects K=3 subsets.
        for p in sorted((N20 / "shadow_cache").glob(
                "oracle_shadow_k5_s*.jsonl")):
            for line in p.open(encoding="utf-8"):
                if not line.strip():
                    continue
                row = json.loads(line)
                frames = {x["frame"]: x for x in row["frames"]}
                shadow_idx[(row["sequence"], int(row["frame"]),
                            int(row["gid"]))] = {
                    "rank_mem": int(row["rank_mem"]),
                    "frames": frames,
                    "max_frame": max(frames) if frames else -1,
                }
        if args.kplus1_model:
            for p in sorted((N20 / args.kplus1_cache_dir).glob("*.jsonl")):
                for line in p.open(encoding="utf-8"):
                    if not line.strip():
                        continue
                    row = json.loads(line)
                    key = (row["sequence"], int(row["frame"]), int(row["gid"]))
                    frames = {x["frame"]: x for x in row["frames"]}
                    shadow_idx_k.setdefault(key, {})[int(
                        row["candidate_rank"])] = {
                        "frames": frames,
                        "is_correct": int(row["is_correct"]),
                    }
    print(f"SHADOW_INDEX k={args.k} entries={len(shadow_idx)}", flush=True)

    # ---- optional learned temporal verifier (sequence-disjoint fold models)
    lv = None
    feat_idx = {}
    if args.learned_verifier:
        from train_n20_temporal_verifier import GRUVerifier
        bundle = torch.load(args.learned_verifier, map_location="cpu")
        feat_cols = bundle["feature_cols"]
        lvh = int(bundle["h"])
        seq_to_fold = bundle["seq_to_fold"]
        fold_models = bundle["fold_models"]
        for row in csv.DictReader((N20 / "features" /
                                   "shadow_tracklets_cal10.csv").open(
                                       newline="", encoding="utf-8")):
            key = (row["sequence"], int(row["frame"]), int(row["gid"]))
            feat_idx.setdefault(key, []).append(row)
        lv = {"feat_cols": feat_cols, "h": lvh,
              "seq_to_fold": seq_to_fold, "fold_models": fold_models,
              "gru_cls": GRUVerifier}
        print(f"LEARNED_VERIFIER h={lvh} threshold={args.verifier_threshold}",
              flush=True)

    # ---- optional K+1 set-level model
    kp = None
    kp_feat_idx = {}
    if args.kplus1_model:
        from train_n20_kplus1 import SharedGRUSet
        bundle = torch.load(args.kplus1_model, map_location="cpu")
        model = SharedGRUSet(len(bundle["feature_cols"]))
        model.load_state_dict(bundle["model"])
        model.eval()
        kp = {"model": model, "feat_cols": bundle["feature_cols"],
              "h": int(bundle["h"]), "threshold": args.verifier_threshold,
              "margin": args.kplus1_margin}
        ds_path = Path(args.kplus1_dataset) if args.kplus1_dataset else \
            N20 / "features" / "shadow_kplus1_cal10.csv"
        for row in csv.DictReader(ds_path.open(newline="", encoding="utf-8")):
            key = (row["sequence"], int(row["frame"]), int(row["gid"]))
            kp_feat_idx.setdefault(key, []).append(row)
        print(f"KPLUS1_MODEL h={kp['h']} threshold={kp['threshold']} "
              f"margin={kp['margin']}", flush=True)

    gt_cache = {}
    z_cache = {}
    q_cache = {}

    def get_gt(seq):
        if seq not in gt_cache:
            gt_cache[seq] = load_gt(seq)
        return gt_cache[seq]

    def get_z(seq):
        if seq not in z_cache:
            z = np.load(CACHE / f"{seq}.npz")
            qz = np.load(CACHE / f"{seq}_queries.npz")
            emb = z["emb"].astype(np.float32)
            emb = emb / (np.linalg.norm(emb, axis=1, keepdims=True) + 1e-8)
            qemb = qz["qemb"].astype(np.float32)
            qemb = qemb / (np.linalg.norm(qemb, axis=1, keepdims=True) + 1e-8)
            r0p = N20 / "gfn_cache_r0" / f"{seq}.npz"
            if r0p.exists():
                rz = np.load(r0p)
                r0g = rz["r0g"]
                r0q = rz["r0q"]
                rz.close()
            else:
                f4 = torch.from_numpy(z["feat4"].astype(np.float32))
                f5 = torch.from_numpy(z["feat5"].astype(np.float32))
                qf4 = torch.from_numpy(qz["qfeat4"].astype(np.float32))
                qf5 = torch.from_numpy(qz["qfeat5"].astype(np.float32))
                r0g = head_embed(gfn, f4, f5).numpy()
                r0q = head_embed(gfn, qf4, qf5).numpy()
            z_cache[seq] = {
                "frames": z["frames"], "offsets": z["offsets"],
                "boxes": z["boxes"], "scores": z["scores"], "emb": emb,
                "r0g": r0g, "r0q": r0q,
                "qgids": [int(g) for g in qz["gids"]],
                "qemb": qemb,
            }
            z.close()
            qz.close()
        return z_cache[seq]

    def write_fn(seq, f, gid, delivered, source, delivery_score, ident):
        z = get_z(seq)
        frames, offsets, dets, emb = (z["frames"], z["offsets"],
                                      z["boxes"], z["emb"])
        r0g, r0q = z["r0g"], z["r0q"]
        o = int(np.searchsorted(frames, f))
        lo = int(offsets[o - 1]) if o > 0 else 0
        hi = int(offsets[o])
        if hi == lo:
            return 0.0
        ious = np.asarray([iou(b, delivered) for b in dets[lo:hi]])
        best = int(np.argmax(ious))
        if ious[best] < 0.5:
            return 0.0
        gfn_e = emb[lo + best]
        r0_e = r0g[lo + best]
        qidx = {g: i for i, g in enumerate(z["qgids"])}
        qi = qidx.get(gid)
        if qi is None:
            return 0.0
        qe_h = z["qemb"][qi]
        qe_r0 = r0q[qi]
        prev_box = ident.prev_delivered_box
        if source in ("p0_tid", "p0") and delivery_score is not None and \
                float(delivery_score) >= 0.5 and prev_box is not None and \
                iou(delivered, prev_box) >= 0.5:
            ident.heur_slots.append((f, gfn_e.copy()))
            if len(ident.heur_slots) > 8:
                ident.heur_slots.pop(0)
        feats = {
            "gfn_sim_human_root": float(gfn_e @ qe_h),
            "r0_sim_human_root": float(r0_e @ qe_r0),
            "gfn_sim_oracle_last": "",
            "gfn_sim_oracle_max": "",
            "r0_sim_oracle_max": "",
            "gfn_sim_heur_last": "",
            "gfn_sim_heur_max": "",
            "gfn_margin_h": "",
            "det_score": delivery_score if delivery_score is not None else 0.0,
            "box_area": float((delivered[2] - delivered[0]) *
                              (delivered[3] - delivered[1])),
            "temporal_iou": float(iou(delivered, prev_box))
            if prev_box is not None else 0.0,
            "center_delta": "",
            "consecutive_delivered": max(0, ident.delivered_streak - 1),
            "missing_streak": ident.missing_streak,
            "crowd": hi - lo,
            "overlap_max": "",
            "nearest_det_distance": "",
            "heur_memory_age": "",
            "oracle_memory_age": "",
            "candidate_age": f - ident.anchor_frame,
            "slots_oracle_count": min(len(ident.memory_slots), 2),
            "slots_heur_count": len(ident.heur_slots),
            "source": source,
        }
        mem_embs = []
        mem_r0s = []
        for sf, sbox in ident.memory_slots[-2:]:
            o2 = int(np.searchsorted(frames, sf))
            lo2 = int(offsets[o2 - 1]) if o2 > 0 else 0
            hi2 = int(offsets[o2])
            if hi2 == lo2:
                continue
            ious2 = np.asarray([iou(b, sbox) for b in dets[lo2:hi2]])
            b2 = int(np.argmax(ious2))
            if ious2[b2] >= 0.5:
                mem_embs.append(emb[lo2 + b2])
                mem_r0s.append(r0g[lo2 + b2])
        if mem_embs:
            gsims = [e @ gfn_e for e in mem_embs]
            rsims = [e @ r0_e for e in mem_r0s]
            feats["gfn_sim_oracle_last"] = float(gsims[-1])
            feats["gfn_sim_oracle_max"] = float(max(gsims))
            feats["r0_sim_oracle_max"] = float(max(rsims))
            feats["oracle_memory_age"] = f - ident.memory_slots[-1][0]
        if len(ident.heur_slots):
            hs = np.stack([s[1] for s in ident.heur_slots[-8:]]) @ gfn_e
            feats["gfn_sim_heur_last"] = float(hs[-1])
            feats["gfn_sim_heur_max"] = float(hs.max())
            feats["heur_memory_age"] = f - ident.heur_slots[-1][0]
        sims_all = emb[lo:hi] @ qe_h
        if len(sims_all) > 1:
            order = np.argsort(-sims_all)
            feats["gfn_margin_h"] = float(
                sims_all[order[0]] - sims_all[order[1]])
        if hi - lo > 1:
            other = np.delete(dets[lo:hi], best, axis=0)
            ov = [iou(b, delivered) for b in other]
            feats["overlap_max"] = float(max(ov))
            cc = ((delivered[0] + delivered[2]) / 2,
                  (delivered[1] + delivered[3]) / 2)
            dc = np.stack([((b[0] + b[2]) / 2, (b[1] + b[3]) / 2)
                           for b in other])
            dd = np.hypot(dc[:, 0] - cc[0], dc[:, 1] - cc[1])
            feats["nearest_det_distance"] = float(np.min(dd))
        if prev_box is not None:
            c0 = ((delivered[0] + delivered[2]) / 2,
                  (delivered[1] + delivered[3]) / 2)
            c1 = ((prev_box[0] + prev_box[2]) / 2,
                  (prev_box[1] + prev_box[3]) / 2)
            feats["center_delta"] = float(
                np.hypot(c0[0] - c1[0], c0[1] - c1[1]))
        x = to_feature_vec(feats)
        x = (x - mean) / std
        with torch.inference_mode():
            p = float(torch.sigmoid(writer(torch.from_numpy(x[None]))).item())
        return p

    cfg.write_fn = write_fn

    def recovery_fn(seq, f, qbox, qframe, gid=None):
        return None

    def shadow_start_fn(seq, f, gid, qbox, qframe):
        if args.dump_only:
            return None
        if kp is not None:
            key = (seq, f, gid)
            entry = shadow_idx_k.get(key)
            if entry is not None and all(
                    rank in entry for rank in range(1, args.k + 1)):
                rows = kp_feat_idx.get(key, [])
                ranks = {int(r["candidate_rank"]) for r in rows}
                if all(r in ranks for r in range(1, args.k + 1)):
                    return f"S:{seq}:{f}:{gid}"
            return None
        entry = shadow_idx.get((seq, f, gid))
        if entry is not None and entry["rank_mem"] <= args.k:
            return f"S:{seq}:{f}:{gid}"
        return None

    def shadow_step_fn(seq, f, gid, sid, elapsed):
        if args.dump_only:
            return {"verdict": "REJECT"}
        parts = sid.split(":")
        key = (parts[1], int(parts[2]), int(parts[3]))
        if kp is not None:
            sf = key[1]
            if f < sf + kp["h"]:
                return {"verdict": "PENDING"}
            rows = kp_feat_idx.get(key, [])
            if not rows:
                return {"verdict": "REJECT"}
            seqs = {}
            for r in rows:
                seqs.setdefault(int(r["candidate_rank"]), []).append(r)
            vecs = []
            valid = True
            for rank in range(1, args.k + 1):
                rs = sorted(seqs.get(rank, []),
                            key=lambda r: int(r["evidence_step"]))
                rs = [r for r in rs if int(r["evidence_step"]) <= kp["h"]]
                if not rs:
                    valid = False
                    break
                v = []
                for r in rs:
                    v.append([to_float(r[c]) for c in kp["feat_cols"]])
                while len(v) < kp["h"]:
                    v.append(v[-1])
                vecs.append(np.nan_to_num(
                    np.asarray(v, dtype=np.float32), nan=0.0))
            if not valid or len(vecs) != args.k:
                return {"verdict": "REJECT"}
            arr = torch.from_numpy(np.stack(vecs))[None]  # (1,K,H,D)
            mask = torch.ones(1, args.k)
            with torch.inference_mode():
                probs = torch.softmax(kp["model"](arr, mask), 1)[0].numpy()
            best = int(np.argmax(probs))
            if best >= 1 and probs[best] >= kp["threshold"]:
                others = np.delete(probs, best)
                if probs[best] - others.max() >= kp["margin"]:
                    entry = shadow_idx_k.get(key, {}).get(best)
                    if entry is not None:
                        traj = {ff: (None if y["box"] is None
                                     else np.asarray(y["box"], dtype=float))
                                for ff, y in entry["frames"].items()
                                if ff >= f}
                        x = entry["frames"].get(f)
                        if x is not None and x["box"] is not None:
                            return {"verdict": "ACCEPT", "traj": traj,
                                    "box": x["box"], "commit_frame": f,
                                    "kplus1_best": best,
                                    "kplus1_probs": [round(float(p), 4)
                                                     for p in probs]}
            return {"verdict": "REJECT"}
        entry = shadow_idx.get(key)
        if entry is None:
            return {"verdict": "REJECT"}
        sf = key[1]
        gt = get_gt(seq)
        if f >= sf + args.horizon:
            x = entry["frames"].get(f)
            traj = {ff: (None if y["box"] is None
                         else np.asarray(y["box"], dtype=float))
                    for ff, y in entry["frames"].items()
                    if ff >= f}
            if lv is not None:
                # learned verifier: causal features from the shadow dataset
                rows = sorted(feat_idx.get(key, []),
                              key=lambda r: int(r["evidence_step"]))
                rows = [r for r in rows if int(r["evidence_step"]) <= lv["h"]]
                if rows and x is not None and x["box"] is not None:
                    vecs = []
                    for r in rows:
                        vecs.append([to_float(r[c]) for c in lv["feat_cols"]])
                    while len(vecs) < lv["h"]:
                        vecs.append(vecs[-1])
                    arr = torch.from_numpy(np.nan_to_num(
                        np.asarray(vecs, dtype=np.float32), nan=0.0))[None]
                    fold = lv["seq_to_fold"].get(seq)
                    if fold is not None:
                        m = lv["gru_cls"](len(lv["feat_cols"]))
                        m.load_state_dict(lv["fold_models"][fold]["gru"])
                        m.eval()
                        with torch.inference_mode():
                            p = float(torch.sigmoid(
                                m(arr).squeeze(-1)).item())
                        if p >= args.verifier_threshold:
                            return {"verdict": "ACCEPT", "traj": traj,
                                    "box": x["box"], "commit_frame": f}
                return {"verdict": "REJECT"}
            if x is not None and x["box"] is not None:
                gf = gt.get(f)
                if gf is not None and gid in gf.gt_ids:
                    tgt = np.asarray(
                        gf.boxes[gf.gt_ids.index(gid)], dtype=float)
                    if iou(np.asarray(x["box"], dtype=float), tgt) >= 0.5:
                        return {"verdict": "ACCEPT", "traj": traj,
                                "box": x["box"], "commit_frame": f}
            return {"verdict": "REJECT"}
        if f >= sf + cfg.shadow_timeout:
            return {"verdict": "TIMEOUT"}
        return {"verdict": "PENDING"}

    out_dir = N20 / "full_loop_oracle_shadow"
    out_dir.mkdir(parents=True, exist_ok=True)
    missing_rows = []
    for seq in seqs:
        gt = get_gt(seq)
        p0 = load_p0(seq)
        num_frames = max(gt.keys()) + 1 if gt else 0
        if args.limit_frames:
            num_frames = min(num_frames, args.limit_frames)
        t0 = time.time()
        result = run_full_loop(seq, gt, p0, num_frames, cfg,
                               recovery_fn, None, None, None,
                               shadow_start_fn, shadow_step_fn)
        elapsed = time.time() - t0
        metrics = aggregate_metrics(seq, result, cfg)
        metrics["runtime_s"] = round(elapsed, 1)
        tag2 = f"_{tag}_s{args.shard}" if args.nshards > 1 else f"_{tag}"
        with (out_dir / f"events{tag2}.jsonl").open(
                "a", encoding="utf-8") as f:
            for e in result["trace"]:
                e["sequence"] = seq
                f.write(json.dumps(e, ensure_ascii=False) + "\n")
        with (out_dir / f"transactions{tag2}.jsonl").open(
                "a", encoding="utf-8") as f:
            for t in result["transactions"]:
                f.write(json.dumps(t, ensure_ascii=False) + "\n")
        with (out_dir / f"metrics{tag2}.csv").open(
                "a", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=list(metrics.keys()))
            if f.tell() == 0:
                w.writeheader()
            w.writerow(metrics)
        if not args.dump_only:
            gt = get_gt(seq)
            seen = set()
            for t in result["transactions"]:
                key = (t["sequence"], int(t["frame"]), int(t["gid"]))
                if key in seen or key in shadow_idx:
                    continue
                seen.add(key)
                gf = gt.get(int(t["frame"]))
                if gf is None or t["gid"] not in gf.gt_ids:
                    continue
                missing_rows.append({"sequence": t["sequence"],
                                     "frame": t["frame"], "gid": t["gid"],
                                     "target_present": 1})
        print(json.dumps(metrics, ensure_ascii=False), flush=True)
    if missing_rows:
        mp = N20 / "shadow_cache" / f"missing_attempts_{tag}.csv"
        with mp.open("w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=list(missing_rows[0].keys()))
            w.writeheader()
            w.writerows(missing_rows)
        print(f"MISSING_ATTEMPTS {len(missing_rows)} -> {mp}", flush=True)
    print("DELAYED_LOOP_DONE", flush=True)


if __name__ == "__main__":
    main()
